# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UlWDv2vXA-qXe6EJEQJLerbMJuFH02C_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

"""Importing Dataset"""

df=pd.read_csv('/content/iris.csv')

df

df.head()

df.head(10)

df.tail()

df.shape

df.isnull().sum()

df.dtypes

data=df.groupby('Species')

data.head()

df['Species'].unique()

df.info()

"""Visulizing the dataset"""

plt.boxplot(df['Sepal.Length'])

plt.boxplot(df['Sepal.Width'])

plt.boxplot(df['Petal.Length'])

plt.boxplot(df['Petal.Width'])

sns.heatmap(df.corr())

"""Data Preparation

"""

df.drop(columns="Id")

sp={'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3}

X=df.iloc[:,0:4]

X

Y=df.iloc[:,4]

Y

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)

"""Training Model

"""

model=LinearRegression()

model.fit(X,Y)

model.score(X,Y)

model.coef_

model.intercept_

"""Making Predictions"""

y_pred=model.predict(X_test)

"""Model Evolution"""

print("Mean squared error: %.2f" %np.mean((y_pred-Y_test)**2))